### ISSUE TITLE
Install nvm and node 5.9

### ISSUE THREAD

**Issue by at15** [at15/lnmp#10]
since 6.0 is still under test .... better just use 5.x
- [x] install nvm using curl
- [x] install node ~~5.9~~ 6.9
- [ ] clean nvm cache, ie: downloaded tar ball, extracted source code
- [x] ~~update php7 branch~~
- [x] ~~update box~~

Ref 

- Ansible nvm https://github.com/leonidas/ansible-nvm/blob/master/tasks/main.yml

**Comment by at15** [comment]
now 6.9 is LTS, so guess this issue need update along with #12

**Comment by ComMouse** [comment]
seems that nvm has an option to install the latest LTS version

**Comment by at15** [comment]
@ComMouse 

````sh
nvm install lts/*
nvm alias default lts/*
````

Added in 9f7cb37b0088a3c07e1fbd59f7cc69a9e2a37f30
