### ISSUE TITLE
Install and config zsh

### ISSUE THREAD

**Issue by at15** [at15/lnmp#2]
- [ ] install zsh
- [ ] install omz
- [ ] enable common plugins

**Comment by at15** [comment]
@arrowrowe any idea?

**Comment by arrowrowe** [comment]
```
sudo apt-get install zsh git-core
```

Then follow [the Basic Instalation of OMZ](https://github.com/robbyrussell/oh-my-zsh#basic-installation).

**Comment by at15** [comment]
I mean ... common plugins ....

**Comment by arrowrowe** [comment]
不用插件... 不过可以推荐下 [ag](https://github.com/ggreer/the_silver_searcher) / [jq](https://github.com/stedolan/jq) / [git-radar](https://github.com/michaeldfallen/git-radar) 之类的......

**Comment by at15** [comment]
well, I think I will just have git enabled for them, but I don't know if it will work properly in vagrant.

**Comment by at15** [comment]
changed my mind, bash is enough.
