### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by at15** [at15/lnmp#3]
though most projects are using php5.x, php7 has been out for a while, and many frameworks we are using or plan to use support it, ie: Laravel, phalcon. 
- should we taught in php5 / php7
- should the box using sth like phpbrew to install multiple version of php

Ref:
- https://github.com/phpbrew/phpbrew

**Comment by at15** [comment]
@ComMouse @arrowrowe @LukeXuan any idea?

**Comment by arrowrowe** [comment]
Though should not, I never cared about an exact version. Have been always relying on @at15 @ComMouse @LukeXuan about this......

**Comment by LukeXuan** [comment]
remi on rhel support multiple version.
I think 5.6 may be proper.

**Comment by at15** [comment]
currently the box is using php5.6, but for new projects, we may use php7 for bettter performance and cleaner code. I think I can create a new branch called `php7` and have a new box called `lnmp-php7`. I don't think using a version manage tool for vagrant boxes is a good idea. besides, `phpbrew` need compile, which may lead to some trouble. 

@ComMouse what's your opinion?

**Comment by at15** [comment]
guess I will just use php5 for master branch, I think I need to figure out how to have both php5 and php7 installed on ubuntu...

**Comment by at15** [comment]
now working on the `feature/php7` branch, and need to config phpstorm 

https://confluence.jetbrains.com/display/PhpStorm/Working+with+Remote+PHP+Interpreters+in+PhpStorm

**Comment by at15** [comment]
can't have phpmyadmin installed, maybe it's time to find a better alternative like https://github.com/vrana/adminer/  ... adminer UI sucks ....
